### ISSUE TITLE
Check off materials that the user already has, using the inventory api

### ISSUE THREAD

**Issue by Powersource** [xanthics/gw2craft#26]
This can be done clientside which is nice.

(as a possible other feature, let users have the option to prefer to use materials that they already have, but I digress (and I see you mentioned that that would take extra processing power))

**Comment by Powersource** [comment]
The forum thread seems to be the only documentation on it so far. https://forum-en.guildwars2.com/forum/community/api/Launching-inventory-endpoints

**Comment by xanthics** [comment]
Unfortunately I do not have, and am unlikely to have in the foreseeable future, time to add that type of check-listing or creating an offline version .

**Comment by Kantharr** [comment]
Hey,


Sorry I haven't been replying. I have been pretty busy lately lol. It's cool, I know how us developers are with time management (I need to manage my time better lol). Thanks for the informative replies though :). I am actually currently working on a C# trading post application. It is almost ready for beta testing but I haven't been working on it lately because of personal reasons. Your site helped me level up my crafting fast and efficiently! Keep up the good work!


-Avo Hunter (Kantharr.2308)

Sent from Yahoo Mail on Android

**Comment by xanthics** [comment]
API material request has been added.
